apiVersion: v1
kind: Pod
metadata:
  name: http-server
  namespace: default
  labels:
    app: http-server
spec:
  containers:
  - name: go-http-server
    image: mczerwinski673/go-http-server:0.1
    ports:
    - containerPort: 8080
